cheap:
  model: 'gemini-1.5-flash'
  temperature: 0.7
  max_output_tokens: 1000
  cost:
    input_tokens: 0.075 # per million tokens
    output_tokens: 0.30 # per million tokens

expensive:
  model: 'gemini-1.5-pro'
  temperature: 0.7
  max_output_tokens: 1000
  cost:
    input_tokens: 0.25 # Note: Update with actual Pro model pricing
    output_tokens: 0.75 # Note: Update with actual Pro model pricing
