name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      country:
        description: 'Countries to deploy (se,no)'
        required: true
        type: choice
        options:
          - se
          - no
          - 'se,no'

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        country: ${{ fromJSON('["' + github.event.inputs.country + '"]') }}

    steps:
      - name: Checkout development repository
        uses: actions/checkout@v3
        with:
          repository: jonkan999/race-aggregator
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: master

      - name: Checkout production repository
        uses: actions/checkout@v3
        with:
          repository: jonkan999/race-aggregator-production
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: master

      - name: Deploy to Production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          COUNTRY: ${{ matrix.country }}
        run: |
          # Debug: Print current directory
          pwd
          ls -la

          # Deploy to Firebase prod target
          firebase deploy --token "$FIREBASE_TOKEN" --only hosting:${COUNTRY}prod
