name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        country: [se, no]

    steps:
      - name: Checkout production repository
        uses: actions/checkout@v3
        with:
          repository: jonkan999/race-aggregator-production
          token: ${{ secrets.PRODUCTION_PAT }}
          ref: master

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          COUNTRY: ${{ matrix.country }}
        run: |
          # Debug: Print current directory
          pwd
          ls -la

          # Deploy to Firebase prod target
          firebase deploy --token "$FIREBASE_TOKEN" --only hosting:${COUNTRY}prod
