name: Force Push to Production

on:
  workflow_dispatch:

jobs:
  force_push_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: jonkan999/race-aggregator
          token: ${{ secrets.PRODUCTION_PAT }}
          ref: master

      - name: Add the production repository as a remote
        run: |
          git remote add production https://github.com/jonkan999/race-aggregator-production.git
          git fetch production

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Force push to production
        run: |
          git push production master --force
