name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        country: [se]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: jonkan999/race-aggregator-production
          token: ${{ secrets.PRODUCTION_PAT }}
          ref: master

      - name: Debug Files
        run: |
          echo "Current directory:"
          pwd
          echo "\nListing root directory:"
          ls -la
          echo "\nListing build directory:"
          ls -la build/
          echo "\nFirebase config files:"
          cat .firebaserc
          cat firebase.json

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          COUNTRY: ${{ matrix.country }}
        run: |
          # Debug Firebase project
          firebase projects:list --token "$FIREBASE_TOKEN"

          # Deploy to Firebase prod target
          firebase deploy --token "$FIREBASE_TOKEN" --only hosting:${COUNTRY}prod
