name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      country:
        description: 'Countries to deploy (se,no)'
        required: true
        default: 'se'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        country: ${{ fromJson('[' + join(split(github.event.inputs.country, ','), ',') + ']') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          COUNTRY: ${{ matrix.country }}
        run: |
          # Verify build directory exists
          if [ ! -d "build/$COUNTRY" ]; then
            echo "No build directory found for $COUNTRY"
            exit 1
          fi

          # Deploy to Firebase prod target
          firebase deploy --token "$FIREBASE_TOKEN" --only hosting:${COUNTRY}prod
